language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - nightly

allowed_failures:
  - nightly

install:
  - composer install -n

script:
  - vendor/bin/phpunit
